### ISSUE TITLE
[plot legend widget] Legend is blinking when many curves are updated

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#1968] opened 2018-06-27 19:04 UTC
Feedback from @mguijarr. After few fixes to use `item.setData`, his application is still blinking.

- open a plot 1d
- open the legend widget
- create 2 curves
- update curves data every seconds
- The legend widget should blink, while there is nothing to update on its side

Maybe it still could exists a `plot.clear` on his application side. But we could check if we can reproduce the problem.

**Comment by t20100** [comment] 2021-02-26 13:05
I'm closing it: duplicate of  #3345, PR #3346 should fix it.

**Closed by t20100** 2021-02-26 13:05 UTC
