### ISSUE TITLE
[io] Tests failing under windows the same way as previously when using fabio

### ISSUE THREAD

**Issue by vasole** [silx-kit/silx#1274] opened 2017-10-09 12:14 UTC
At least on my machine (Python 3.6.2, silx 0.6.0)

In order to pass the tests, I need to change the line in test_utils.py from:

        if sys.platform == "win32" and fabio is not None:

to 

        if sys.platform == "win32":

**Comment by vasole** [comment] 2017-10-09 12:17
@vallsv @PiRK 

Should the tests be changed or the file utils.py code? (savespec function)

**Comment by vasole** [comment] 2017-10-09 12:34
In my opinion, if that problem happens only under windows, gc.collect should be called in the savespec function when under windows and close_file=True.

**Comment by vallsv** [comment] 2017-10-09 13:09
If the test have nothing to do with fabio (an external library), then we have to find the problem and to fix the code.

The code using `gc.collect` was only needed to use `silx.io.open`, then AFAIK it have nothing to do with `savespec`.

**Comment by vallsv** [comment] 2017-10-09 13:22
To diagnostic that you should come with your computer. I don't see what can explain this behaviour.

**Comment by vallsv** [comment] 2017-10-09 13:27
BTW it would be nice to provide the test backtrace.

**Comment by vasole** [comment] 2017-10-09 13:59
The problem is the same it was happening when using fabio: Unless one calls gc.collect the file descriptor is not liberated despite not having any reference to the file handle.

**Comment by vasole** [comment] 2017-10-09 14:04
The backtrace you have it below, but it is nothing else than what I said above:

![image](https://user-images.githubusercontent.com/5636251/31341919-5fcf299c-ad0b-11e7-90d9-f5aeb9b293d5.png)

**Comment by vasole** [comment] 2017-10-09 14:08
savespec also opens and closes a file. If windows does not free the handle unless calling gc.collect, then in order to respect the "close_file" keyword, I think one should call gc.collect at savespec. 

I need to know if I fix savespec or if I fix the test.

To reproduce the error at your side on a windows machine you will need to uninstall fabio. If fabio is installed gc.collect is always called and the test passes. That is equivalent to "fixing the test". My point is that probably what needs to be fixed is savespec.

**Comment by vasole** [comment] 2017-10-09 14:10
@vallsv 

>> To diagnostic that you should come with your computer. I don't see what can explain this behaviour.

If fabio is not installed, the error we are facing is the same you already faced earlier and that led you to introduce the if block to call gc.collect

**Comment by vasole** [comment] 2017-10-09 14:27
I decided to fix the library and not to fix the test.

**Comment by vallsv** [comment] 2017-10-09 14:29
I only fixed a single problem. The one on fabio. It was occurred by fabio, and it is now fixed on the fabio master. That's is why, if there is a problem on our code, we have to fix the code.

**Comment by vallsv** [comment] 2017-10-09 14:35
I am afraid your patch fix a problem somewhere else, as my `gc.collect` hide something else.

**Comment by vasole** [comment] 2017-10-09 14:37
> I only fixed a single problem. The one on fabio. It was occurred by fabio, and it is now fixed on the fabio master. That's is why, if there is a problem on our code, we have to fix the code.

It is what I have done. I did not patch the test.

**Comment by vasole** [comment] 2017-10-09 14:39
I agree it could be hiding a problem on the testing procedure itself.

**Comment by vallsv** [comment] 2017-10-09 15:45
I can confirm the problem is not there. Ill push a patch https://github.com/silx-kit/silx/pull/1276

- I created a `test.dat` file without `savespec` 
- I only execute `python run_tests.py silx.io.test.test_utils.TestOpen.testSpec`
- Without the patch it fail, without it's OK
- Then I use back `savespec`, and it is still fine

**Closed** 2017-10-10 12:03 UTC
