### ISSUE TITLE
[plot] Add arcsinh compression scheme for colormap

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#1212] opened 2017-09-29 07:34 UTC
This is the same as log-scale which goes from  R+* --> R, Arcsinh does R --> R, so there is no "NaN" poping out

**Comment by t20100** [comment] 2017-09-29 14:29
matplotlib has a `SymLogNorm` normalization that is intended for that: https://matplotlib.org/devdocs/api/_as_gen/matplotlib.colors.SymLogNorm.html
Limitation compared to arcsinh is that you have to define a linear section around 0.

It is possible to create a custom normalization for matplotlib.
And for the OpenGL backend, it should be relatively simple.

**Comment by t20100** [comment] 2019-07-08 14:51
closing as duplicate of #2133

**Closed by t20100** 2019-07-08 14:51 UTC
