### ISSUE TITLE
silx 0.14 installation issue: conflict with numpy 1.19.4?

### ISSUE THREAD

**Issue by tdard** [silx-kit/silx#3312] opened 2020-12-01 16:28 UTC
Hi dear fellows,

Before all, I precise that I followed the procedure of [contributing](https://github.com/silx-kit/silx/blob/master/CONTRIBUTING) before opening the issue.

## My configuration
Python 3.7.7
Windows 10

```bash
$ pip list
Package                       Version
----------------------------- -------------
alabaster                     0.7.12
altgraph                      0.17
appdirs                       1.4.4
async-generator               1.10
attrs                         20.3.0
Babel                         2.9.0
backcall                      0.2.0
bleach                        3.2.1
cached-property               1.5.2
certifi                       2020.11.8
chardet                       3.0.4
colorama                      0.4.4
coverage                      5.3
cycler                        0.10.0
Cython                        0.29.21
decorator                     4.4.2
defusedxml                    0.6.0
docutils                      0.16
entrypoints                   0.3
fabio                         0.10.2
future                        0.18.2
h5py                          3.1.0
idna                          2.10
imagesize                     1.2.0
importlib-metadata            3.1.0
ipykernel                     5.3.4
ipython                       7.19.0
ipython-genutils              0.2.0
jedi                          0.17.2
Jinja2                        2.11.2
jsonschema                    3.2.0
jupyter-client                6.1.7
jupyter-core                  4.7.0
jupyterlab-pygments           0.1.2
kiwisolver                    1.3.1
lxml                          4.6.2
Mako                          1.1.3
MarkupSafe                    1.1.1
matplotlib                    3.3.3
mistune                       0.8.4
nbclient                      0.5.1
nbconvert                     6.0.7
nbformat                      5.0.8
nbsphinx                      0.8.0
nest-asyncio                  1.4.3
numpy                         1.19.3
packaging                     20.7
pandoc                        1.0.2
pandocfilters                 1.4.3
parso                         0.7.1
pefile                        2019.4.18
pickleshare                   0.7.5
Pillow                        8.0.1
pip                           20.3
ply                           3.11
prompt-toolkit                3.0.8
Pygments                      2.7.2
pyinstaller                   4.2.dev0
pyinstaller-hooks-contrib     2020.10
pyopencl                      2020.3.1+cl21
PyOpenGL                      3.1.5
pyparsing                     2.4.7
PyQt5                         5.15.2
PyQt5-sip                     12.8.1
pyrsistent                    0.17.3
python-dateutil               2.8.1
pytools                       2020.4.3
pytz                          2020.4
pywin32                       300
pywin32-ctypes                0.2.0
pyzmq                         20.0.0
qtconsole                     5.0.1
QtPy                          1.9.0
requests                      2.25.0
scipy                         1.5.4
setuptools                    50.3.2
silx                          0.13.3b0
six                           1.15.0
snowballstemmer               2.0.0
Sphinx                        3.3.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
testpath                      0.4.4
tornado                       6.1
traitlets                     5.0.5
urllib3                       1.26.2
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.36.0
zipp                          3.4.0

```

## What is my problem?
I am trying to install silx 0.14 on my local machine on Windows 10, but I obtain an error

## What did I do to trigger the error?
After downloading the clone of my fork, I ran the two following commands:
```bash
C:\Users\Tristan\silx>git checkout 0.14
C:\Users\Tristan\silx>pip install .
```
Here is the error that I obtain:

```bash
C:\Users\Tristan\silx>pip install .
Processing c:\users\tristan\silx
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... - ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\tristan\appdata\local\programs\python\python37\python.exe' 'c:\users\tristan\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Tristan\AppData\Local\Temp\tmpzv240ww4'
         cwd: C:\Users\Tristan\AppData\Local\Temp\pip-req-build-kono0a7p
    Complete output (25 lines):
    INFO:silx.setup:Use setuptools with cython
    Traceback (most recent call last):
      File "c:\users\tristan\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "c:\users\tristan\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "c:\users\tristan\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\Tristan\AppData\Local\Temp\pip-build-env-a75_rl31\overlay\Lib\site-packages\setuptools\build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\Tristan\AppData\Local\Temp\pip-build-env-a75_rl31\overlay\Lib\site-packages\setuptools\build_meta.py", line 254, in run_setup
        self).run_setup(setup_script=setup_script)
      File "C:\Users\Tristan\AppData\Local\Temp\pip-build-env-a75_rl31\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 992, in <module>
        setup_package()
      File "setup.py", line 987, in setup_package
        setup_kwargs = get_project_configuration(dry_run)
      File "setup.py", line 840, in get_project_configuration
        import numpy
      File "C:\Users\Tristan\AppData\Local\Temp\pip-build-env-a75_rl31\overlay\Lib\site-packages\numpy\__init__.py", line 305, in <module>
        _win_os_check()
      File "C:\Users\Tristan\AppData\Local\Temp\pip-build-env-a75_rl31\overlay\Lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
        raise RuntimeError(msg.format(__file__)) from None
    RuntimeError: The current Numpy installation ('C:\\Users\\Tristan\\AppData\\Local\\Temp\\pip-build-env-a75_rl31\\overlay\\Lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\tristan\appdata\local\programs\python\python37\python.exe' 'c:\users\tristan\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Tristan\AppData\Local\Temp\tmpzv240ww4' Check the logs for full command output.

```

## What are my thoughts
After a careful check [here](https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html) and [there](https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an/64661876#64661876) I could reasonably determine that the problem comes from a requirement that is installed with numpy 1.19.4

I tried to bypass this by setting up a fixed version of numpy: 1.19.3. 
So I changed one line of silx's setup.py: 
l.862: `setup_requires = ["setuptools", "numpy==1.19.3", "Cython>=0.21.1"]`
Then I ran:

```bash
C:\Users\Tristan\silx>pip install .
Processing c:\users\tristan\silx
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Some build dependencies for file:///C:/Users/Tristan/silx conflict with the backend dependencies: numpy==1.19.4 is incompatible with numpy==1.19.3.
```

## Where I need help
But it shows that one of the dependencies MUST work with numpy 1.19.4, but the sanity checks causes the error.

Do you know how to fix that, or at least how to have a temporary alternative? 

Kind regards,

Tristan

**Comment by kif** [comment] 2020-12-01 16:49
On Tue, 01 Dec 2020 08:29:06 -0800
tdard <notifications@github.com> wrote:

> pip                           20.3

Hi,

Apparently pip 20.3 (came out yesterday) is changing a lot the way
dependencies are managed.

Could you please try with a former version of pip to check if it works ?

**Comment by tdard** [comment] 2020-12-01 17:04
Hi, 

Thank you Jerôme.
I just tried with pip 20.2 and I still have the error.

**Comment by t20100** [comment] 2020-12-02 15:14
I reproduced on Windows10, python3.8.

The discussion is pointed out by the exception: https://tinyurl.com/y3dm3h86
I haven't read all, but solution is for now: `pip install numpy==1.19.3` (before installing silx if installed from source, if installed from wheels, it can be any time).

I doubt there is anything we can do at our level.

**Comment by tdard** [comment] 2020-12-02 15:33
Hi Thomas, 

Thank you for your time.  
I encountered this issue while having numpy 1.19.3 already installed on my local machine.

I never tried to install numpy 1.19.4 by myself. 
To me, it looks like one of the dependencies "forces" the use of numpy 1.19.4 .
I could successfully install silx 0.13, but not silx 0.14 (neither the 0.14 branch nor 0.14.0-rc1 tag).

The wheels can be installed without any issue, the problem that I have is when I try to build from source.

**Comment by t20100** [comment] 2020-12-02 15:38
OK, when building from source, `silx` takes the currently installed version of `numpy` as the minimal version, and if it needs to install `numpy` or to install `numpy` in a temporary folder to build silx wheel, it takes the latest version... which does not work.

BTW, for testing, we build wheels here: https://silx.gitlab-pages.esrf.fr/bob/silx/ (currently some snapshot of 0.14 branch since we are preparing the release).

**Comment by tdard** [comment] 2020-12-02 16:18
Alright, so here is what I also tried:
Considering that the `pip install .` did not work even though I had numpy 1.19.3, I tried to run the `setup.py` file directly:
```bash
$ python setup.py clean
$ python setup.py build
$ python setup.py install
```
And it display no error, and the installation seems done perfectly:
`Finished processing dependencies for silx==0.14.0rc1`

I doubled check my virtual environment with `pip list` and it shows that the package is installed:
`silx                          0.14.0rc1`

_However_, when I run python and import silx, a new error arises:
```python
$ python
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (A
MD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import silx
Traceback (most recent call last):
  File "C:\Users\Tristan\silx\silx\__init__.py", line 58, in <module>
    from ._version import __date__ as date  # noqa
ModuleNotFoundError: No module named 'silx._version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Tristan\silx\silx\__init__.py", line 61, in <module>
    raise RuntimeError("Do NOT use %s from its sources: build it and use the built
 version" % project)
RuntimeError: Do NOT use silx from its sources: build it and use the built version
```

Do you have an idea of where error does this comes from? It looks more like an user issue than something in the code, but I've been not able to track down what is missing... A path problem maybe? Did I do something wrong with this installation procedure?

Kind regards,
Tristan

**Comment by t20100** [comment] 2020-12-02 16:42
You need to move away from `silx` source directory to start python and `import silx`, else it tries using the sources and since there is some compiled code it would fail sooner or later, so we make it fail sooner with a `Do NOT use silx from its sources` message.

**Comment by tdard** [comment] 2020-12-03 08:14
Thank you @t20100, that was it!

So to summarize:
- `pip install .` on the source code generates the error with numpy 1.19.4, regardless of the version of numpy I already had
- However,  
```bash
python setup.py build
python setup.py install
```
enabled me to install silx correctly.

Thank you for all your help, and good luck with your work at ESRF!

Tristan

**Comment by t20100** [comment] 2020-12-03 09:55
Good to know you made it work.

I'm closing this issue, since there is nothing we can do at our level, root cause is an issue in Windows10.
Please reopen if needed.

**Closed by t20100** 2020-12-03 09:55 UTC
