### ISSUE TITLE
Auto-scale graph does not work as expected

### ISSUE THREAD

**Issue by andygotz** [silx-kit/silx#131] opened 2016-07-04 09:14 UTC
When un-selecting a plot using the Legends control box I expect that when I then click on Auto-scale the plot will resize using only the values in the remaining (selected) plots. This does not happen and the plot appears with the same axes as if the un-selected plot was still there. Auto-scale does not seem to re-calculate the min and max of the graph. 

It would be nice if the plot re-calcuted the min+max taking into account only the active plots.

Andy

**Comment by t20100** [comment] 2016-07-05 08:59
Also check if resize is working as expected when curves are moved to right axis

**Comment by t20100** [comment] 2016-07-05 15:53
I could not reproduce this...

In IPython:
```
In [1]: from silx.gui.plot import plot1D
In [2]: %pylab qt
In [3]: plt = plot1D((1, 2))
In [4]: plt.addCurve((0, 1), (10, 11), legend='2')
```
Then unselecting a curve in the Legend widget and doing a reset zoom works.

**Comment by t20100** [comment] 2016-07-07 09:34
Tested with same data, it works.
2 options:
- Problem specific to a machine or
- Missunderstanding of autoscale toggling icons functions.

For second issue, we can provide more information about the function in the toolbar:
- Add more info to X and Y autoscale tooltips.
- Disable the reset zoom icon when no axis is in autoscale mode, change at least the tooltip and possibly the icon depending on X and Y autoscale mode to reflect this.
- When enabling autoscale on an axis also do a zoom reset.

**Comment by vasole** [comment] 2016-07-07 15:49
Should we open a specific issue asking for an enhancement? In fact what we are now missing is to apply the autoscale on the seen region if the X axis is fixed.

**Comment by t20100** [comment] 2016-07-08 14:46
Closing now as not reproduced and PR #171 adds info to button.
Open issue #179 for changing reset zoom behavior.

**Closed by t20100** 2016-07-08 14:46 UTC
Labels: invalid
