### ISSUE TITLE
[plot] numpy RuntimeWarning All-Nan slice encountered when using logarithmic scale

### ISSUE THREAD

**Issue by UUSim** [silx-kit/silx#2752] opened 2019-09-20 12:07 UTC
When I plot data using logarithmic view I get the following warning:

```
/usr/local/lib/python3.5/dist-packages/silx/gui/plot/items/core.py:920: RuntimeWarning: All-NaN axis encountered
  numpy.nanmin(x),
/usr/local/lib/python3.5/dist-packages/silx/gui/plot/items/core.py:921: RuntimeWarning: All-NaN slice encountered
  numpy.nanmax(x),
/usr/local/lib/python3.5/dist-packages/silx/gui/plot/items/core.py:922: RuntimeWarning: All-NaN axis encountered
  numpy.nanmin(y),
/usr/local/lib/python3.5/dist-packages/silx/gui/plot/items/core.py:923: RuntimeWarning: All-NaN slice encountered
  numpy.nanmax(y)
/usr/local/lib/python3.5/dist-packages/silx/gui/plot/PlotWidget.py:502: RuntimeWarning: All-NaN axis encountered
  xMin = numpy.nanmin([xMin, bounds[0]])
/usr/local/lib/python3.5/dist-packages/silx/gui/plot/PlotWidget.py:503: RuntimeWarning: All-NaN slice encountered
  xMax = numpy.nanmax([xMax, bounds[1]])
/usr/local/lib/python3.5/dist-packages/silx/gui/plot/PlotWidget.py:510: RuntimeWarning: All-NaN axis encountered
  yMinLeft = numpy.nanmin([yMinLeft, bounds[2]])
/usr/local/lib/python3.5/dist-packages/silx/gui/plot/PlotWidget.py:511: RuntimeWarning: All-NaN slice encountered
  yMaxLeft = numpy.nanmax([yMaxLeft, bounds[3]])
```

Details:
Numpy: 1.12.1
Python: 3.5.3
silx: 0.10.0

This is the data:
```
x: [ 0.      0.0064  0.0128  0.0192  0.0256  0.032   0.0384  0.0448  0.0512  0.0576]
y: [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
dtype: float64
```

This is the the call for plotting:
`plot.addCurve(x, y, resetzoom=True)`

Plotting itself does appear to work without crashing.

**Comment by t20100** [comment] 2019-09-20 12:42
There's a few place where such warnings are mute, this seems like a place where it is missing.
It is done this way to save checking of all NaNs data and relies on `nanmin|max` returned value.
All this needs checking.

**Comment by t20100** [comment] 2021-02-26 12:45
I'm closing it, I could not reproduce with current tip of the project (and numpy 1.19.4).
Please reopen if needed.

**Closed by t20100** 2021-02-26 12:45 UTC
