### ISSUE TITLE
[Plot] NameError raised when running doctest on PlotTools

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#185] opened 2016-07-12 13:11 UTC
On some systems, a "NameError: name 'numpy' is not defined" is raised when running tests using code from PlotTools docstrings.

These docstring tests are duplicate of the test suites in testPlotTools.py, so they have been (temporarily?) removed before doing release 0.2.0 (see #184).

This problem only seems to affect my office computer (both for python 2.7.9 and python 3.4.2) and one of my laptops at home, but not anyone else's office computer.

**Comment by t20100** [comment] 2016-07-12 18:07
3 options:
- Try adding numpy to test environment with setUp argument of doctest.DocTestSuite
- Change the sample code so that callbacks does not depend on a module
- Change your computers...

**Comment by vallsv** [comment] 2016-07-18 09:44
Here is the same, reproduced with Debian 8, Python 2.7, numpy from the system, silx 0.2 release. I used IPython

```
from PyQt4 import Qt
Qt.QApplication([])
import silx.gui.plot.PlotTools
import doctest
doctest.testmod(silx.gui.plot.PlotTools, optionflags=doctest.ELLIPSIS)
```
You have to click on one of the widgets to display the error message. And the message is displayed many times.
```
ERROR:silx.gui.plot.PlotTools:Error while converting coordinates (57.291667, 98.611111)with converter 'Radius'
ERROR:silx.gui.plot.PlotTools:Traceback (most recent call last):
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/PlotTools.py", line 192, in _plotEvent
    value = func(x, y)
  File "<doctest silx.gui.plot.PlotTools.PositionInfo[7]>", line 2, in <lambda>
NameError: global name 'numpy' is not defined
```

**Comment by vallsv** [comment] 2016-07-18 09:51
I also have the same with ```run_tests.py -i```, from silx source code with a hack to use ```positionInfoTestSuite``` in the test suite

**Comment by vallsv** [comment] 2017-01-25 13:34
I close it. It looks to be fixed by some way.

**Comment by PiRK** [comment] 2017-01-25 15:22
Dirty fix, on a release day: https://github.com/silx-kit/silx/commit/c829b27c6c7da8ad862f500066aa5ada438eaac4
We still don't know what causes this.

**Comment by vallsv** [comment] 2017-01-25 16:38
Ah ok, then should we open it back?

**Comment by PiRK** [comment] 2017-01-26 07:11
To me it looks like an obscure error in `doctest` that we will never be able to fix. So I don't have any issue with permanently keeping the test disabled, and I vote for keeping this issue closed (label wontfix). 
The only drawback is that the source code in the docstring is no longer part of the continuous integration, so we need to pay more attention when we change the API to keep it up to date.

**Comment by PiRK** [comment] 2017-01-26 07:42
I did a little bit of extra investigation. If I enable the doctest again, the error appears if I run the entire plot test suite (`python run_tests.py -i silx.gui.plot.test.suite`) but it does not appear when I run only testPlotTools (`python run_tests.py -i silx.gui.plot.test.testPlotTools.suite`).

It seems that a previous test is breaking something. It could be similar to #538, but now the console tests are deactivated.

**Comment by PiRK** [comment] 2017-01-26 08:41
More debugging:

Test causing the error message to be displayed:
    - `python run_tests.py -i silx.gui.plot.test.testPlotInteraction.suite silx.gui.plot.test.testPlotTools.suite`
    - `python run_tests.py -i silx.gui.plot.test.testMaskToolsWidget.suite silx.gui.plot.test.testPlotTools.suite`
    - `python run_tests.py -i silx.gui.plot.test.testPlotWindow.suite silx.gui.plot.test.testPlotTools.suite`
    - `python run_tests.py -i silx.gui.plot.test.testProfile.suite silx.gui.plot.test.testPlotTools.suite`

All other combinations of testPlotTools and another test from the `gui.plot.test` suite  don't cause the error (testColors, testCurvesROIWidget, testStackView)

**Comment by PiRK** [comment] 2017-01-26 09:21
One very ugly way to solve the problem is to replace the docstring code with:
```
    >>> from silx.gui.plot.PlotTools import PositionInfo
    >>> import numpy
    >>> def radius(x, y, numpy=numpy):
    ...     return numpy.sqrt(x*x + y*y)
    >>> def angle(x, y, numpy=numpy):
    ...     return numpy.degrees(numpy.arctan2(y, x))
    >>> position = PositionInfo(plot=plot, converters=[
    ...     ('Radius', radius),
    ...     ('Angle', angle)])
    >>> toolBar.addWidget(position)  # Add the widget to the toolbar
    <...>
    >>> plot.show()  # To display the PlotWindow with the position widget
```

But this ruins the documentation value of the docstring.

Before that test, we tried:
```
    >>> def radius(x, y):
    ...     import numpy
    ...     return numpy.sqrt(x*x + y*y)
    >>> def angle(x, y):
    ...     import numpy
    ...     return numpy.degrees(numpy.arctan2(y, x))
```

End we ended up with the error:
```
  File "/users/knobel/git/silx/build/lib.linux-x86_64-2.7/silx/gui/plot/PlotTools.py", line 194, in _plotEvent
    value = func(x, y)
  File "<doctest silx.gui.plot.PlotTools.PositionInfo[8]>", line 2, in angle
ImportError: __import__ not found
```

So the local namespace inside the functions seems to be completely empty.

**Comment by t20100** [comment] 2021-02-26 15:22
Closing, we don't use `doctest` since a while.

**Closed by t20100** 2021-02-26 15:22 UTC
