### ISSUE TITLE
[build] please add dependecies to install_requires

### ISSUE THREAD

**Issue by picca** [silx-kit/silx#1043] opened 2017-08-17 11:31 UTC
Hello, in order to automatically generate the right dependencies for the Debian package, I need to add all this.

```
diff --git a/setup.py b/setup.py
index 852c48d..f91cc03 100644
--- a/setup.py
+++ b/setup.py
@@ -649,7 +649,22 @@ def get_project_configuration(dry_run):
         # for most of the computation
         "numpy",
         # for the script launcher
-        "setuptools"]
+        "setuptools",
+        # Debian added
+        "ipython",
+        "qtconsole",
+        "enum34",
+        "fabio",
+        "h5py",
+        "lxml",
+        "mako",
+        "matplotlib",
+        "PyOpenGL",
+        "pil",
+        "pyopencl",
+        "PyQt5",
+        "scipy",
+        "six"
+    ]
```

thanks for considering.

**Comment by picca** [comment] 2017-08-17 11:34
I forgot six

**Comment by vallsv** [comment] 2017-08-17 11:52
Hi,

We don't want to have much dependencies, that's why all our dependencies are optional.

If there is a way to know we are building a Debian package, i think we can add all of this, else i am pretty sure it will not be accepted. If there is no way to have this information, maybe we can create an env var to custom that (like `SILX_INCLUDE_OPTIONAL_DEPENDENCIES`).

**Comment by vallsv** [comment] 2017-08-17 11:53
I edit your message to as `six` and avoid mistake.

**Comment by vallsv** [comment] 2017-08-17 12:01
Well, the idea of `SILX_INCLUDE_OPTIONAL_DEPENDENCIES` is not the right one while there is very specific dependencies (like `PyQt5`)...

**Comment by picca** [comment] 2017-08-17 12:02
At some point users need all these dependencies installed to use silx.

without pyqt5, matploltib etc.. no silx view.
for the optionals dependencies I think that we should look at extras_dependencies or something like that from setuptools.

**Comment by picca** [comment] 2017-08-17 12:04
what about this

http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by picca** [comment] 2017-08-17 12:08
To my opinion, if import silx.<module> or something similar end up with an ImportError
This should be fixed by adding the module to install_depends.

for real optional dependencies extra seems the way to go :)

**Comment by vallsv** [comment] 2017-08-17 12:58
Sounds interesting but for matplotlib and Qt i still dont know own we can use it. I see the need for the applications, but our library expect:
- one of PyQt4, PyQt5, PySide
- at one point should be able to work with at least one of matplotlib, pyopengl

Maybe this targets can be part of requirement provided by an env var.

BTW, did you see the `requirements.txt` files? Do you think something like that can be used in your build process. It would be easier to create specific requirement for your usecase.

**Comment by picca** [comment] 2017-08-17 13:12
What is the problem with matplotlib ?
So you run all your gui test with the three qt toolkits ?

I red about this requirements.txt but If I understand correctly this is something which allows to make the connection between virtual dependencies (expressed in the setup.py) and the one of your provided (pip).

the install_requieres are here to tech setuptools which dependencies should be installed in order to have a working silx. So it seems to me that for now 0.5.0 the right dependencies are PyQt5 (no more support of QT4) and matplotlib + OpenGL.

When you speak about the support of PyQt4 and PySide (there is no more support of the upstream)
This is for jessie, wheezy ?

Cheers

**Comment by vallsv** [comment] 2017-08-17 13:25
>  So you run all your gui test with the three qt toolkits ?

Yes

We also run our GUI tests on Windows, and Mac OS X; plus Python 2.7, 3.4, 3.5, 3.6; plus with/without some optionals dependencies. That's a big combination of environments. Fortunately we do not test everything :-)

**Comment by picca** [comment] 2017-08-17 13:29
Great :), So maybe we can put PyQt5 aside and I will maintain a Debian specific patch for this dependency.

**Comment by picca** [comment] 2017-08-17 13:30
From my point of view you need one toolkit and the only right nowaday is PyQt5 ;)

**Comment by picca** [comment] 2017-08-17 13:32
```
:~/Projets/hkl$ rmadison python-pyqt5
python-pyqt5 | 5.3.2+dfsg-3  | oldstable           | amd64, arm64, armel, armhf, i386, mips, mipsel, powerpc, ppc64el, s390x
python-pyqt5 | 5.3.2+dfsg-3  | oldstable-kfreebsd  | kfreebsd-amd64, kfreebsd-i386
python-pyqt5 | 5.7+dfsg-5    | stable              | amd64, arm64, armel, armhf, i386, mips, mips64el, mipsel, ppc64el, s390x
python-pyqt5 | 5.7+dfsg-5+b1 | testing             | amd64, arm64, armel, armhf, i386, mips, mips64el, mipsel, ppc64el, s390x
python-pyqt5 | 5.7+dfsg-5+b1 | unstable            | amd64, arm64, armel, armhf, hurd-i386, i386, kfreebsd-amd64, kfreebsd-i386, mips, mips64el, mipsel, powerpc, ppc64el, s390x
python-pyqt5 | 5.8.2+dfsg-1  | experimental        | armel, armhf, hurd-i386, kfreebsd-i386, mipsel
python-pyqt5 | 5.9+dfsg-1    | buildd-experimental | powerpc
python-pyqt5 | 5.9+dfsg-1    | experimental        | amd64, arm64, i386, kfreebsd-amd64, mips, mips64el, powerpc, ppc64el, s390x
```

which version of PyQT5 are you testing ?

**Comment by vallsv** [comment] 2017-08-17 13:41
We always tests the last release. Here it is `PyQt5-5.9-5.9.1-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl` on Linux. Except if there is a regression on there side: for example we are using `PyQt5 5.8.2` on Windows.

**Comment by picca** [comment] 2017-08-17 13:45
Ok in that case once activted the test will be done also for a bunch of different version of PyQt5 thanks to the Debian buildd :))

**Comment by picca** [comment] 2017-08-17 17:24
Hello, here an error I got after installing
```
picca@ORD03037:~/tmp$ silx view
Traceback (most recent call last):
  File "/usr/bin/silx", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_worki
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'enum34' distribution was not found and is required by silx
```

So the enum34 dependency should be optional.

**Comment by picca** [comment] 2017-08-17 17:26
Something like 'enum34;python_version<"3.4"'

**Comment by vallsv** [comment] 2017-08-18 07:09
Which remind me that it is not so simple, cause it is part of our `third_party`. And only Debian remove our embedded third party modules.

**Comment by picca** [comment] 2017-08-18 09:41
why bothering with third_party when it is available via pip ?

**Comment by vallsv** [comment] 2017-08-18 10:02
Because our politics is to avoid strong dependencies. That is way you also can see `six` on our third party.

**Comment by t20100** [comment] 2018-10-23 12:35
We've added a `full` `extra_requires` target in the `setup.py`.
With `pip` you can do `pip install silx[full] to get all the optional dependencies.
Maybe this help for the debian packaging.

**Comment by t20100** [comment] 2018-10-23 12:37
Closing for now as some dependencies will remain optionals (e.g., a least when there are multiple options like PyQt5 or PySide2)

**Closed by t20100** 2018-10-23 12:37 UTC
