### ISSUE TITLE
[plot] exception while displaying a 1d curve with vertical logscale

### ISSUE THREAD

**Issue by vallsv** [silx-kit/silx#645] opened 2017-03-02 16:07 UTC
The curve is well displayed. It looks to be a problem with the mouse event.

```
Traceback (most recent call last):
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 292, in mouseMoveEvent
    FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 1958, in motion_notify_event
    self.callbacks.process(s, event)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/cbook.py", line 549, in process
    proxy(*args, **kwargs)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/cbook.py", line 416, in __call__
    return mtd(*args, **kwargs)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/BackendMatplotlib.py", line 787, in _onMouseMove
    self._plot.onMouseMove(event.x, event.y)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/Plot.py", line 2691, in onMouseMove
    self._eventHandler.handleEvent('move', inXPixel, inYPixel)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/PlotInteraction.py", line 1488, in handleEvent
    self._eventHandler.handleEvent(event, *args, **kwargs)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/Interaction.py", line 192, in handleEvent
    return handler(*args, **kwargs)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/PlotInteraction.py", line 1003, in onMove
    marker = self.machine.plot._pickMarker(x, y)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/Plot.py", line 2529, in _pickMarker
    markers = self._backend.pickItems(x, y)
  File "/home/valls/.local/lib/python2.7/site-packages/silx/gui/plot/BackendMatplotlib.py", line 832, in pickItems
    self.fig.pick(mouseEvent)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/artist.py", line 459, in pick
    a.pick(mouseevent)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 3770, in pick
    martist.Artist.pick(self, args[0])
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/artist.py", line 459, in pick
    a.pick(mouseevent)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/artist.py", line 448, in pick
    for a in self.get_children():
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/axis.py", line 722, in get_children
    majorticks = self.get_major_ticks()
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/axis.py", line 1320, in get_major_ticks
    numticks = len(self.get_major_locator()())
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/ticker.py", line 1938, in __call__
    return self.tick_values(vmin, vmax)
  File "/home/valls/.local/lib/python2.7/site-packages/matplotlib/ticker.py", line 1964, in tick_values
    "Data has no positive values, and therefore can not be "
ValueError: Data has no positive values, and therefore can not be log-scaled.
```

**Comment by t20100** [comment] 2017-03-06 13:18
I could not reproduce, can you provide the case that makes this happen?

**Comment by vasole** [comment] 2017-04-12 10:36
If this cannot be reproduced ....

**Comment by t20100** [comment] 2018-02-21 15:56
Closing as not reproducible. Feel free to reopen with failing sample code.

**Closed by t20100** 2018-02-21 15:56 UTC
