### ISSUE TITLE
cannot load any more object with static TLS

### ISSUE THREAD

**Issue by woutdenolf** [silx-kit/silx#3102] opened 2020-06-05 16:06 UTC
I've seen this issue many times before but can't find an issue regarding it. I've been able to solve it by changing import order but that's not very elegant.

```python
# Debian 8, python 3.7
python run_tests.py silx.opencl.test.test_linalg.TestLinAlg.test_gradient -v
```

Exception:

```python
======================================================================
ERROR: test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test
Traceback (most recent call last):
  File "/users/denolf/.pyenv/versions/3.7.6/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/test/__init__.py", line 33, in <module>
    from . import test_backprojection
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/test/test_backprojection.py", line 47, in <module>
    from .. import backprojection
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/backprojection.py", line 39, in <module>
    from .sinofilter import SinoFilter
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/opencl/sinofilter.py", line 41, in <module>
    from ..math.fft.clfft import CLFFT, __have_clfft__
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/math/__init__.py", line 39, in <module>
    from .medianfilter import medfilt, medfilt1d, medfilt2d
  File "/mntdirect/_data_id21_inhouse/wout/dev/silx/build/lib.linux-x86_64-3.7/silx/math/medianfilter/__init__.py", line 30, in <module>
    from .medianfilter import (medfilt, medfilt1d, medfilt2d)
ImportError: dlopen: cannot load any more object with static TLS
```

**Comment by payno** [comment] 2020-08-26 10:00
Sorry I guess we miss this one.
I am meeting the same issue.
Can you tell the import you reordered ? Did the modification where pushed in the branch ?

**Comment by woutdenolf** [comment] 2020-08-26 10:43
If I recall correctly the trick was to import the things that cause the TLS exception (e.g. medianfilter) explicitly before importing other libraries.

**Comment by payno** [comment] 2020-08-26 11:03
ok thanks :)

**Comment by vasole** [comment] 2020-08-26 12:05
I have found this googling around:

```
Something in the chain of imports was not C/C++ compiled with -gPIC flag.

Importing that library causes a problem that turns all imports to "static TLS". 
There is a maximum amount of such "static TLS" slots (names I use here are surely incorrect). 
Exact N of slots depends on the OS, and how it was compiled.
```

**Comment by t20100** [comment] 2020-08-26 12:09
AFAIK `-fPIC` is used.
It looks to be related to using OpenMP (which makes sense since the issue is about Thread Local Storage), disabling it makes it work.
There's looks to be quite a few Python project with issues opened about this.

**Comment by vasole** [comment] 2020-08-26 12:11
Yep. Reading a bit further ```there is a mention that it is OpenMP which was compiled without the flag causing the cascade.```

**Comment by payno** [comment] 2020-08-26 12:22
I can confirm that works without open mp.

**Comment by payno** [comment] 2020-08-26 12:24
So I guess this is outside the scope of silx ? We can close the issue ?

**Comment by t20100** [comment] 2020-08-26 12:33
Yes I guess it's a won't fix...

A few solutions though:

-Solution 1: Compile silx with the `--no-openmp` flag.
-Solution 2 (not tested but looks good): LD_PRELOAD libgomp (from https://itectec.com/matlab/matlab-openmp-mex-files-static-tls-problem/)... or load packages/libs using OpenMP first.
-Solution 3: Use an up-to-date operating system since it seems to not happen on recent OS.

**Closed** 2020-08-27 06:18 UTC
Labels: wontfix
