### ISSUE TITLE
Problem with opening data using h5todict

### ISSUE THREAD

**Issue by mjjank** [silx-kit/silx#3160] opened 2020-07-17 14:58 UTC
Can not open dataset, for others in this same file it works, like i.e. sample_0001: 3.1

```
h5todict('/data/ID10/inhouse/blc12103/id10/blc12103_id10.h5', 'sample_0001: 4.1/measurement/')



Traceback (most recent call last):

  File "<ipython-input-495-c9c410a16356>", line 1, in <module>
    h5todict('/data/ID10/inhouse/blc12103/id10/blc12103_id10.h5', 'sample_0001: 4.1/measurement/')

  File "C:\Users\jankowsk\AppData\Local\Continuum\anaconda3\lib\site-packages\silx\io\dictdump.py", line 311, in h5todict
    if is_group(h5f[path + "/" + key]):

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "C:\Users\jankowsk\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\_hl\group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py\h5o.pyx", line 190, in h5py.h5o.open

KeyError: 'Unable to open object (bad version number for layout message)'
```

**Comment by mjjank** [comment] 2020-07-17 16:42
To supplement, here ara datasets which open and some with errors:

sample_0001: 3.1/measurement/

sample_0001: 4.1/measurement/

'Unable to open object (bad version number for layout message)'
sample_0001: 5.1/measurement/

"Unable to open object (can't locate ID)"
sample_0001: 7.1/measurement/

sample_0001: 8.1/measurement/

sample_0001: 9.1/measurement/

"Unable to open object (can't locate ID)"
sample_0001: 10.1/measurement/

"Unable to open object (can't locate ID)"
sample_0001: 19.1/measurement/

sample_0001: 20.1/measurement/

sample_0001: 21.1/measurement/

sample_0001: 22.1/measurement/

sample_0001: 23.1/measurement/

sample_0001: 24.1/measurement/

sample_0001: 25.1/measurement/

sample_0001: 26.1/measurement/

sample_0001: 27.1/measurement/

sample_0001: 28.1/measurement/

sample_0001: 29.1/measurement/

sample_0001: 30.1/measurement/

sample_0001: 31.1/measurement/

sample_0001: 32.1/measurement/

sample_0001: 33.1/measurement/

sample_0001: 34.1/measurement/

sample_0001: 35.1/measurement/

sample_0001: 36.1/measurement/

sample_0001: 37.1/measurement/

sample_0001: 38.1/measurement/

sample_0001: 39.1/measurement/

sample_0001: 40.1/measurement/

sample_0001: 41.1/measurement/

sample_0001: 42.1/measurement/

sample_0001: 43.1/measurement/

Can't read data (inflate() failed)
sample_0001: 45.1/measurement/

sample_0001: 46.1/measurement/

sample_0001: 47.1/measurement/

sample_0001: 48.1/measurement/

sample_0001: 49.1/measurement/

sample_0001: 50.1/measurement/

sample_0001: 51.1/measurement/

sample_0001: 52.1/measurement/

sample_0001: 53.1/measurement/

sample_0001: 54.1/measurement/

sample_0001: 55.1/measurement/

sample_0001: 56.1/measurement/

sample_0001: 57.1/measurement/

"Unable to open object (can't locate ID)"
sample_0001: 58.1/measurement/

sample_0001: 59.1/measurement/

sample_0001: 60.1/measurement/

sample_0001: 61.1/measurement/

sample_0001: 62.1/measurement/

'Unable to open object (bad version number for layout message)'
sample_0001: 63.1/measurement/

sample_0001: 64.1/measurement/

sample_0001: 65.1/measurement/

sample_0001: 66.1/measurement/

'Unable to open object (bad version number for layout message)'
sample_0001: 67.1/measurement/

sample_0001: 68.1/measurement/

sample_0001: 69.1/measurement/

'Unable to open object (bad version number for layout message)'
sample_0001: 70.1/measurement/

'Unable to open object (bad version number for layout message)'
sample_0001: 71.1/measurement/

'Unable to open object (bad version number for layout message)'
sample_0001: 75.1/measurement/

sample_0001: 76.1/measurement/

sample_0001: 77.1/measurement/

sample_0001: 78.1/measurement/

sample_0001: 79.1/measurement/

'Unable to open object (bad version number for layout message)'
sample_0001: 80.1/measurement/

sample_0001: 81.1/measurement/

sample_0001: 82.1/measurement/

sample_0001: 83.1/measurement/

'Unable to open object (bad version number for layout message)'
sample_0001: 84.1/measurement/

sample_0001: 85.1/measurement/

sample_0001: 86.1/measurement/

'Unable to open object (bad version number for layout message)'
sample_0001: 87.1/measurement/

'Unable to open object (bad version number for layout message)'
sample_0001: 88.1/measurement/

**Comment by mjjank** [comment] 2020-07-17 16:45
Ok, seems to be that there are some borken links, but in general data was not moved form the folder.

**Comment by t20100** [comment] 2020-07-21 11:45
Could you tell us which version of silx and h5py and which operating system?

Print version numbers:
```
import silx, h5py
silx.version, h5py.version.version, h5py.version.hdf5_version
```

With `silx` 0.13.0, `h5py` 2.10.0 and `libhdf5` 1.10.4, I cannot reproduce the `'Unable to open object (bad version number for layout message)'`. I would suspect that you are reading the file with an older version of `libdf5` than the one that was used to write it.

The `Unable to open object (can't locate ID)` errors are due to broken links, each time the links in the `measurement` group are pointing to not existing datasets, e.g., in `sample_0001: 5.1`: `measurement/elapsed_time` points to `instrument/elapsed_time/data` which does not exists. The links are within the file, so it is not a problem of moving the files or not, it is a problem that some datasets are missing in the file.

The `Can't read data (inflate() failed)` in `sample_0001: 5.1` is probably due to compressed dataset `elapsed_time` and `epoch` being corrupted (I could read the others).

**Comment by vallsv** [comment] 2020-07-21 12:12
It also could be external links no?

**Comment by t20100** [comment] 2020-07-21 12:14
In this case it is broken soft (i.e., internal) links.

**Comment by t20100** [comment] 2020-07-21 12:16
I am looking how to make `h5todict` resilient to issues in files (at least broken links).

**Comment by mjjank** [comment] 2020-07-21 12:18
import silx, h5py
silx.version, h5py.version.version, h5py.version.hdf5_version
Out[144]: ('0.12.0', '2.8.0', '1.8.20')

I am using anaconda on Win 10. I did today: `conda update conda` and the errors are there.

**Comment by t20100** [comment] 2020-07-21 12:25
Do you know how the file was written? I would really suspect that hdf5 version `1.10.x` was used, while you are using hdf5 version `1.8.20`.
Conda provides hdf5 `1.10.6` (https://anaconda.org/conda-forge/hdf5), try `conda update hdf5 h5py`.

That's one part of the issues, the others are due to issues in the file itself.

**Comment by mjjank** [comment] 2020-07-21 12:39
I was using the ID10 beamline max computer, it was ~ one month ago during experiment blc12103. Maybe BLISS env was updated since this time by BCU, hard to say.  After update of libraries:
  
'Unable to open object (component not found)'
'Unable to open object (component not found)'
'Unable to open object (component not found)'
Can't read data (inflate() failed)
'Unable to open object (component not found)'

import silx, h5py
silx.version, h5py.version.version, h5py.version.hdf5_version
Out[3]: ('0.12.0', '2.10.0', '1.10.4')

**Comment by t20100** [comment] 2020-07-21 12:42
So it was indeed an issue with the version of HDF5.
For the remaining issues which are issues in the file, I will make a pull request to print errors for the `Unable to open object (component not found)` (borken links) and skip those, but the error `Can't read data (inflate() failed)` will probably remain.

**Comment by mjjank** [comment] 2020-07-21 12:43
Ok, why the data is corrupted, it could be that we had some errors during scans. It is BLISS problem?

**Comment by t20100** [comment] 2020-07-21 13:18
Maybe... else someone modifying the file.

**Comment by woutdenolf** [comment] 2020-07-21 13:59
The softlinks under "measurement" are links to datasets under "instrument". These links are created before the datasets are created. So it can happen that some or all links are broken when you stop the scan very shortly after starting it (no data collected yet).
![image](https://user-images.githubusercontent.com/7264703/88063839-c9c00d00-cb6a-11ea-9f60-bafc61a23cc6.png)

**Comment by woutdenolf** [comment] 2020-07-21 14:22
The dataset `43.1/measurement/elapsed_time` is corrupt however, which is worrying. Was this file opening by anyone during the experiment? And if so, which tools and versions?

**Comment by mjjank** [comment] 2020-07-21 15:22
Yes, the files are continuously open during the experiment to plot the data. We have PyMca 5.5.4 on the beamline and sometimes use silx to open the data.  The current version is 

EH1_EXP [1]: import silx               
EH1_EXP [2]: silx.version              
    Out [2]: '0.13.0-rc2'

EH1_EXP [3]:  

I don't know what was the version one month ago. It is a little bit scary that the data is not protected against corruption. I thought it was reported some time ago and solve, protection what I mean. The data can be accessed from remote computers with different versions of silx and pymca.

**Comment by woutdenolf** [comment] 2020-07-21 15:43
The HDF5 file is locked by the writer, which is meant to protect against corruption. However software that needs to look at the file during the experiment is bypassing that lock. What is the output of 'print(os.environ.get("HDF5_USE_FILE_LOCKING"))'? It should be `None` or `True`.

**Comment by mjjank** [comment] 2020-07-21 16:40
Hehe, interesting:

H1_EXP [2]: import os         
EH1_EXP [3]: print(os.environ.get("HDF5_USE_FILE_LOCKING"))   
FALSE
EH1_EXP [4]:

**Comment by woutdenolf** [comment] 2020-07-21 16:45
Ok we'll have to figure out what sets this environment variable and remove it. The Nexus writer resets `HDF5_USE_FILE_LOCKING=TRUE` but other software which is run in the same environment is likely not as cautious.

**Comment by woutdenolf** [comment] 2020-07-21 16:51
It is set in /users/blissadm/local/blissenv.ini. Remove the line with HDF5_USE_FILE_LOCKING.

**Comment by vasole** [comment] 2020-07-21 17:34
I do not know who is the bliss contact of ID10. Concerning ID11 I sent a mail to the beamline responsible and the bliss contact on June 23 saying they should avoid setting that environment variable.

**Comment by mjjank** [comment] 2020-07-21 18:21
I will inform our contact (its LC).

**Comment by laurent-claustre** [comment] 2020-07-22 07:35
Hi all, I don't understand, the variable HDF5_USE_FILE_LOCKING = FALSE was requested by DAU to allow silx in the bliss conda environment to open the file during the scan, otherwise one cannot open the file.
What did change with h5py?
Since 2018, the ansible recipe we use to deploy conda and bliss on beamline computers set the HDF5_USE_FILE_LOCKING in blissenv.ini and .bashrc.

We can remove this from ansible recipe, If I understand well, since recent h5py, we do not need to use the var., nexus_writer locks the file but other h5py programs can now open the file in read mode without problem and if one try to open the file in append mode it will failed because the file is locked. 

This can only work if all the software at ESRF are using recent h5py version.
Question, what about old software running on NICE for instance, which use old h5py version?

**Comment by vasole** [comment] 2020-07-22 08:00
In order to ensure there is no possibility of file curruption, HDF5_USE_FILE_LOCKING = TRUE or undefined.

If you set the variable to FALSE, any process will be able to open the file in write mode. Depending on the version of h5py, you may end up having append mode as the default.

Since it is preferable to block the access to a file than to corrupt it, that variable should not be set.

**Comment by vasole** [comment] 2020-07-28 08:00
Can this be closed?

**Comment by t20100** [comment] 2020-08-25 07:09
PR #3162 (still opened) should close it.

**Closed** 2020-10-16 11:14 UTC
