### ISSUE TITLE
Freeze in Spyder

### ISSUE THREAD

**Issue by kif** [silx-kit/silx#410] opened 2016-11-15 09:40 UTC
When run in Spyder (win python - windows7), there is an python embedded console.
then: 
```
   %gui qt
   from six.gui.plot import Plot1D
```

just locks everything. looks like a dead lock.

**Comment by payno** [comment] 2016-11-29 07:58
Did you wait until the '%gui qt' command ended ? 
We had some kermel crah under notebook sometime if the %gui qt is not on a separated cell

**Comment by PiRK** [comment] 2017-04-19 13:08
This could be the same issue as described in #538 (ipython console widget related)

**Comment by t20100** [comment] 2017-11-15 16:07
I could not reproduce this issue neither with Spyder nor with the notebook with WinPython-64bit-3.6.3.0Qt5 (latest version) and silx 0.6.1.

So I'm closing it.

**Closed by t20100** 2017-11-15 16:07 UTC
