### ISSUE TITLE
[plot] gl plot widget not shown in QTabWidget until resize 

### ISSUE THREAD

**Issue by PiRK** [silx-kit/silx#2010] opened 2018-07-11 12:58 UTC
When a plot widget with a gl backend is added to a QTabWidget, it is not shown until the user triggers a resize event.

Configuration: Python 2, PyQt5, backend OpenGl, Qt 5.3.2 (debian8)

```
from silx.gui import qt
from silx.gui.plot import PlotWidget

app = qt.QApplication([])

tab = qt.QTabWidget()

p1 = PlotWidget(backend="gl")
tab.addTab(p1, "1")

tab.show()
app.exec_()
```

**Comment by t20100** [comment] 2018-07-13 08:11
I could not reproduce on my debian8 PC with same packages.
What differs from  your config is the GPU config...

**Comment by PiRK** [comment] 2018-09-04 13:09
I cannot reproduce it with PyQt4. 

I can reproduce it with PyQt5 + Python 3.

My GPU config is very likely a complete mess, for multiple reasons. If no one else can reproduce this, we can close the issue.

**Comment by vasole** [comment] 2018-09-12 08:51
Closed as not reproducible.

**Closed by vasole** 2018-09-12 08:51 UTC
Labels: wontfix
