### ISSUE TITLE
ValueError on opening spec.dat file

### ISSUE THREAD

**Issue by TheGrim1** [silx-kit/silx#1759] opened 2018-03-27 10:29 UTC
I get a strangely irregular error when opening the same .dat specfile in a loop similar to this:

from silx.io.spech5 import SpecH5
for i in range(10):
  sfh5 = SpecH5(spec_fname)   
  scan_list   = sfh5.keys()
  scan_group = '{}.1'.format(i)    
  if scan_group not in scan_list:
    print(scan_list)
    raise ValueError('Scan number {} not found in scan list printed above'.format(scan_group))
  more calculations using sfh5[scan_group]
  sfh5.close()

Every 5-10 attempts to open the specfile fail with this traceback:

Traceback:
    sfh5 = SpecH5(spec_fname)   
  File "/mntdirect/_data_id13_inhouse6/COMMON_DEVELOP/py_andreas/aj_venv/local/lib/python2.7/site-packages/silx/io/spech5.py", line 573, in __init__
    scan_group = ScanGroup(scan_key, parent=self, scan=scan)
  File "/mntdirect/_data_id13_inhouse6/COMMON_DEVELOP/py_andreas/aj_venv/local/lib/python2.7/site-packages/silx/io/spech5.py", line 627, in __init__
    self.add_node(MeasurementGroup(parent=self, scan=scan))
  File "/mntdirect/_data_id13_inhouse6/COMMON_DEVELOP/py_andreas/aj_venv/local/lib/python2.7/site-packages/silx/io/spech5.py", line 814, in __init__
    data=scan.data_column_by_name(label),
  File "silx/io/specfile.pyx", line 594, in silx.io.specfile.Scan.data_column_by_name
  File "silx/io/specfile.pyx", line 947, in silx.io.specfile.SpecFile.data_column_by_name
ValueError: negative dimensions are not allowed

I don't want to move the opening of the specfile outside the loop as there are many more calculations steps per loop that don't need it. I can catch the error like this, but I wanted to report the issue nevertheless:
    specfile_open = False
    while not specfile_open:
        try:
            sfh5 = SpecH5(spec_fname)
            specfile_open = True
        except ValueError as msg:
            print(msg)
            print('Got ValueError opening specfile, retrying')

silx.version = '0.7.0'

**Comment by vasole** [comment] 2018-03-28 09:03
The key 0.1 is not expected to be in a SpecH5 file wrapped. Does your first scan in the file starts with a scan numbered 0?

**Comment by TheGrim1** [comment] 2018-03-28 11:52
Yes, I made a mistake in the construction of the example. The error only appears with valid scan numbers, after the loop has run a couple of times (bizzarely).

**Comment by PiRK** [comment] 2018-03-28 12:16
The origin of the error seems to be https://github.com/silx-kit/silx/blob/7046bfbba10154d5bd8701a43af9fe87de794f26/silx/io/specfile.pyx#L947
```
        nlines = specfile_wrapper.SfDataColByName(self.handle,
                                                  scan_index + 1,
                                                  label,
                                                  &data_column,
                                                  &error)
        self._handle_error(error)
        cdef numpy.ndarray ret_array = numpy.empty((nlines,),
                                                   dtype=numpy.double)
```

It could be that `SfDataColByName` fails and returns -1, and `self._handle_error` does not properly do its job of raising a meaningful error. So we hand up trying to initialize an array with a shape of (-1, ). 

But it does not explain it happens intermittently on an identical file. Could it be that your file is updated while the code is running, and sometimes you may find a corrupted scan (incompletely written)?

**Comment by TheGrim1** [comment] 2018-03-28 13:13
I don't want to change the spec file at least. Can i force sfh5 = SpecH5(spec_fname) to read only? Or does sfh5.close() not take care of flushing? As far as I see there is only one access to the file at a time.

**Comment by PiRK** [comment] 2018-03-28 13:29
SpecH5 is always read-only. If there is no other process accessing your file, it should not change. I was worried that another process might be writing the file while you read it.

I would be very interested in inspecting the faulty Spec file. Maybe it just contains a corrupted scan. Does it always fail while reading the same scan number?

**Comment by TheGrim1** [comment] 2018-03-28 14:28
It doesn't seem to fail at the same scan, no. The function I use to loop over the scan numbers searches for h5 datafiles in a data directory. This somewhat randomises in which order thecorresponding spec scans are read. Repeated runs failed at no 56 (after sucessfully reading 72), 67 (after 66) and 72 (after 62).
The function accessing the spec file (/tmp_14_days/silx_spec_error/r1_w3.dat) is /tmp_14_days/silx_spec_error/update_final_spec.py. 

In between loops I do some large calculations and io with the actual data in h5 files, so the os cache is proabably overwritten. I noticed a simple loop opening and closing the spec file runs much faster and does not reproduce the error I get.

**Comment by vasole** [comment] 2018-04-11 09:18
At the python side we should use SfData(sf, idx, &data, &data_info, &error) and make sure data is liberated.

**Comment by PiRK** [comment] 2018-04-18 08:13
I was able to reproduce the error using your file, and I found that every time the error happens it is always in scan 76, which has no data at all. 
We already solved an issue in the past when dealing with empty scans (#756), but this time it seems to be behave in different way.

**Comment by PiRK** [comment] 2018-04-18 09:47
The origin of the error is `SfData` returning -1 without setting the error code (https://github.com/silx-kit/silx/blob/master/silx/io/specfile/src/sfdata.c#L244), so using this function instead of `SfDataColsByName` is not the solution.

**Comment by vasole** [comment] 2018-05-05 10:03
@PiRK I guess this can be closed.

**Comment by vasole** [comment] 2018-05-05 10:05
Added the 0.8 milestone as a reminder.

**Comment by PiRK** [comment] 2018-05-12 10:02
This specific problem with empty scans will not happen again. So we can close the issue.
I am still a bit puzzled by the random occurrences of the bug. I am not capable of explaining why I did not happen all the time.

**Closed by PiRK** 2018-05-12 10:02 UTC
Labels: bug
