### ISSUE TITLE
[silx view] default Y orientation not applied

### ISSUE THREAD

**Issue by woutdenolf** [silx-kit/silx#3098] opened 2020-06-05 13:56 UTC
Not sure it's a bug or a feature but the default Y orientation is not applied when opening a file:
![2020-06-05_15-50-29](https://user-images.githubusercontent.com/7264703/83884219-de744d00-a744-11ea-8d75-6e4dcd726f86.png)

**Comment by vallsv** [comment] 2020-06-05 13:59
Is that a Flint issue ;-)

**Comment by vallsv** [comment] 2020-06-05 14:00
Maybe because it is an NXData?

**Comment by t20100** [comment] 2020-06-16 14:32
I can't reproduce this with current 0.13 tip.

**Comment by t20100** [comment] 2022-09-12 12:36
I'm closing, I still can't reproduce with current main branch.
Please reopen if needed and provide more information on how to reproduce.

**Closed by t20100** 2022-09-12 12:36 UTC
